version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Secret!Passw0rd
      POSTGRES_USER: postgres
      POSTGRES_DB: hrdb
    ports:
        - 5432:5432
    volumes: 
        - ./database.sql:/docker-entrypoint-initdb.d/database.sql
        - db_data:/var/lib/postgresql/data
  hasura: 
    image: hasura/graphql-engine
    ports:
      - 8080:8080
    environment: 
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:Secret!Passw0rd@db:5432/hrdb
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
    depends_on: 
      - db
volumes:
  db_data:
      